ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      bundle install --without production &&
      rails db:migrate &&
      git config --global alias.co checkout && git config --global alias.br branch && git config --global alias.ci commit &&  git config --global alias.st status
    command: >
      rails server
github:
    prebuilds:
        pullRequestsFromForks: true